use xml traversal instead of string method
fictive-reality/vocode-python pull request #10
Opened 2023-09-12 04:07 UTC by julifr

Patches behavior around string method for escaping XML tags to return truncated text.
```                ssml_fragment = ssml[: event["text_offset"]]
                # TODO: this is a little hacky, but it works for now
                return ssml_fragment.split(">")[-1]
```
Interrupting the messages in small windows would occasionally return `ssml` tags if the tags was malformed and the index of the split wasn't properly escaped by `>`.

Solution is to explicit refer to XML tree and namespaces defined in `create_ssml` and extract text directly.

2023-09-12 12:21 UTC, ripperdoc requested changes
removed

2023-09-12 20:07 UTC, julifr commented
More detailed explanation:

Examine `message_sent`:
<img width="258" alt="Screenshot 2023-09-12 at 12 29 27 PM" src="https://github.com/fictive-reality/vocode-python/assets/141594308/01c35fb1-b64b-4371-8a98-360bea8d6cda">

Here we see that part of the `</prosody>` tag has been trimmed and appended to the text.

This is reflected as `ssml_fragment` here:
```
ssml_fragment: <speak xmlns="https://www.w3.org/2001/10/synthesis" xmlns:mstts="https://www.w3.org/2001/mstts" version="1.0" xml:lang="en-US"><voice name="en-US-SteffanNeural"><mstts:silence value="500ms" type="Tailing-exact" /><prosody pitch="0%" rate="15%">Starting my day with a hot cup of coffee.</pr
```


For clarity, we ignore the opening tags for this next example:
```
ssml_fragment: Starting my day with a hot cup of coffee.</pr
```

ssml_fragment = ssml[: event["text_offset"]]
> Here, ssml_fragment is defined as an index of the original `ssml`, where the numerical index of `event["text_offset"]` corresponds to a event["text"] string.
> Ideally, this slices through the string from the beginning of the message to the stop word.

For example, the event prior to this interrupt was:
```
event: {'text': 'ahead', 'text_offset': 289, 'audio_offset': 2.033125, 'boudary_type': <SpeechSynthesisBoundaryType.Word: 0>}
```

`get_message_up_to` returns `ssml_fragment`, as an array of strings delimited by the `>`, indexed to the last element:
`return ssml_fragment.split(">")[-1]`

If all closing tags are present,` </prosody></voice></speak>`,
this would return None this is indexing at the end of `</speak>`.

`get_message_up_to` only applies when an interrupt event occurs.

So, here we have that  `</pr` is malformed.
This is because the end of the tag has not been generated.
The string delimiter fails to account for this behavior.

The more appropriate method would be to index through the message directly instead of parsing SSML.

2023-09-16 02:43 UTC, julifr reviewed
Reviewed.
Approved for revision.

2023-09-16 02:48 UTC, julifr commented
Previously the entire XML tree was being indexed as one string.
Current revision truncates directly on message text by parsing XML tree.
New method indexes only on message text, and only returns message text.
Malformed tags do not leak into message output.

2023-09-16 02:57 UTC, julifr commented
```
        if " " in message:
            silence = ElementTree.SubElement(
                voice_root, "{%s}silence" % NAMESPACES.get("mstts")
            )
            silence.set("strength", "x-weak")
            silence.set("type", "Sentenceboundary")
```

Triggers on any message containing a space.
This is how phrases with 'one or more' words is described.

Silence type is now set to `Sentenceboundary`:
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-structure

Previously silence was appended to every message afterwards.
This is closer to the intent of the inline comments, and considers the behavior that are describing.

```
        # this ugly hack is necessary so we can limit the gap between sentences
        # for normal sentences, it seems like the gap is > 500ms, so we're able to reduce it to 500ms
        # for very tiny sentences, the API hangs - so we heuristically only update the silence gap
        # if there is more than one word in the sentence
```

2023-09-16 02:58 UTC, julifr reviewed
Logging removed.
Aliases and namespaces reverted.

2023-09-18 08:46 UTC, ripperdoc reviewed
a

2023-09-18 09:05 UTC, ripperdoc commented
> We should recreate this as an upstream PR. To do that, I think we need to rewrite it a bit. What I think it need to include is:
> 
> **MRE for the bug**. Basically, a Unit test code that can trigger this behaviour (or if code would get complicated, what action steps in e.g. the vocode CLI apps can reproduce it). `ssml_fragment.split(">")[-1]` should not be able to create a string that ends with `</pr`. What are the pre-conditions that would make this possible? Is the input `ssml_fragment` malformed e.g. `</pr<sometag` (unlikely) or is the `text_offset > len(ssml_fragment)` (no splitting) while the `ssml_fragment` is cutoff from start, e.g. string ends with `</pr`? Without this reproduced, I think any work on fixes is risky.
> 
> **A fix:** The current fix looks like the right strategy in general, but I have some questions on it.
> 
> * Can we always assume text exists in `<prosody>` tags?
> * `text_offset` is indexed from the start of the event text or the start of the message? There can be multiple events in the pool, but just one incoming message string? I'm a bit unclear.
> * You truncate the text in the matching prosody-tag and then return the modified Element tree as a string. That solves that tag, but what if there are more tags after the matching tag? They would also be stringified and returned, but in actuality, we want to remove any tags except those required to close currently opened tags at our position.

To be specific, to add to the code / instructions that generates the error (MRE), I would add an example of what the variables are at when calling `get_message_up_to()`, e.g.:
- What's the contents of `message` and `ssml` and the relevant event(s) from `word_boundary_event_pool`.

2023-09-21 02:02 UTC, julifr commented
Actual MRE code, as requested:

```
import asyncio
from xml.etree import ElementTree

NAMESPACES = {
    "mstts": "https://www.w3.org/2001/mstts",
    "": "https://www.w3.org/2001/10/synthesis",
}

ElementTree.register_namespace("", NAMESPACES[""])
ElementTree.register_namespace("mstts", NAMESPACES["mstts"])

class WordBoundaryEvent:
    def __init__(self, text, text_offset, audio_offset, boundary_type):
        self.text = text
        self.text_offset = text_offset
        self.audio_offset = audio_offset
        self.boundary_type = boundary_type

class WordBoundaryEventPool:
    def __init__(self):
        self.events = []

    def add(self, event):
        self.events.append(
            {
                "text": event.text,
                "text_offset": event.text_offset,
                "audio_offset": (event.audio_offset + 5000) / (10000 * 1000),
                "boundary_type": event.boundary_type,
            }
        )

    def get_events_sorted(self):
        return sorted(self.events, key=lambda event: event["audio_offset"])

class AzureSynthesizer:
    def __init__(self, voice_name="en-US-SteffanNeural"):
        self.voice_name = voice_name

    def create_ssml(self, message: str) -> str:
        ssml_root = ElementTree.fromstring('<speak version="1.0" xmlns="https://www.w3.org/2001/10/synthesis" xml:lang="en-US"></speak>')
        voice = ElementTree.SubElement(ssml_root, "voice")
        voice.set("name", self.voice_name)
        if " " in message:
            silence = ElementTree.SubElement(voice, "{%s}silence" % NAMESPACES.get("mstts"))
            silence.set("value", "500ms")
        prosody = ElementTree.SubElement(voice, "prosody")
        prosody.text = message.strip()
        return ElementTree.tostring(ssml_root, encoding="unicode")

    def word_boundary_cb(self, evt, pool):
        pool.add(evt)

    async def create_speech(self, message, global_pool):
        ssml = self.create_ssml(message)
        self.mock_event_connect(lambda event: self.word_boundary_cb(event, global_pool))
        await self.mock_synthesis_process(message, ssml)

    def mock_event_connect(self, callback):
        self.callback = callback

    async def mock_synthesis_process(self, message, ssml):
        audio_offset_counter = 0
        text_offset_counter = ssml.find(message)

        for word in message.split():
            event = WordBoundaryEvent(word, text_offset_counter, audio_offset_counter, "word")
            self.callback(event)

            audio_offset_for_word = 13375 + len(word) * 1999
            audio_offset_counter += audio_offset_for_word
            text_offset_counter += len(word) + 1
            await asyncio.sleep(0.001)

    def get_message_up_to(self, message: str, ssml: str, seconds: int, pool: WordBoundaryEventPool) -> str:
        events = pool.get_events_sorted()
        for event in events:
            print(event)
            if event["audio_offset"] > seconds:
                print(f"Currently: {event}")
                ssml_fragment = ssml[: event["text_offset"]]
                return ssml_fragment.split(">")[-1]
        return message

async def main():
    synthesizer = AzureSynthesizer()
    global_pool = WordBoundaryEventPool()
    
    messages = ["The quick brown fox jumped over the lay dog.", "Hello world. I am a computer."]
    
    for message in messages:
        await synthesizer.create_speech(message, global_pool)
        ssml = synthesizer.create_ssml(message)
        
        for event in global_pool.get_events_sorted():
            result = synthesizer.get_message_up_to(message, ssml, event["audio_offset"], global_pool)
            print(f"text_offset: {event['text_offset']:.1f}: {result}")

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

This outputs:
```
{'text': 'The', 'text_offset': 201, 'audio_offset': 0.0005, 'boundary_type': 'word'}
{'text': 'quick', 'text_offset': 205, 'audio_offset': 0.0024372, 'boundary_type': 'word'}
Currently: {'text': 'quick', 'text_offset': 205, 'audio_offset': 0.0024372, 'boundary_type': 'word'}
text_offset: 201.0: The 
{'text': 'The', 'text_offset': 201, 'audio_offset': 0.0005, 'boundary_type': 'word'}
{'text': 'quick', 'text_offset': 205, 'audio_offset': 0.0024372, 'boundary_type': 'word'}
{'text': 'brown', 'text_offset': 211, 'audio_offset': 0.0047742, 'boundary_type': 'word'}
Currently: {'text': 'brown', 'text_offset': 211, 'audio_offset': 0.0047742, 'boundary_type': 'word'}
text_offset: 205.0: The quick 
{'text': 'The', 'text_offset': 201, 'audio_offset': 0.0005, 'boundary_type': 'word'}
{'text': 'quick', 'text_offset': 205, 'audio_offset': 0.0024372, 'boundary_type': 'word'}
{'text': 'brown', 'text_offset': 211, 'audio_offset': 0.0047742, 'boundary_type': 'word'}
{'text': 'fox', 'text_offset': 217, 'audio_offset': 0.0071112, 'boundary_type': 'word'}
Currently: {'text': 'fox', 'text_offset': 217, 'audio_offset': 0.0071112, 'boundary_type': 'word'}
text_offset: 211.0: The quick brown 
{'text': 'The', 'text_offset': 201, 'audio_offset': 0.0005, 'boundary_type': 'word'}
{'text': 'quick', 'text_offset': 205, 'audio_offset': 0.0024372, 'boundary_type': 'word'}
{'text': 'brown', 'text_offset': 211, 'audio_offset': 0.0047742, 'boundary_type': 'word'}
{'text': 'fox', 'text_offset': 217, 'audio_offset': 0.0071112, 'boundary_type': 'word'}
{'text': 'jumped', 'text_offset': 221, 'audio_offset': 0.0090484, 'boundary_type': 'word'}
Currently: {'text': 'jumped', 'text_offset': 221, 'audio_offset': 0.0090484, 'boundary_type': 'word'}
text_offset: 217.0: The quick brown fox 
{'text': 'The', 'text_offset': 201, 'audio_offset': 0.0005, 'boundary_type': 'word'}
{'text': 'quick', 'text_offset': 205, 'audio_offset': 0.0024372, 'boundary_type': 'word'}
{'text': 'brown', 'text_offset': 211, 'audio_offset': 0.0047742, 'boundary_type': 'word'}
{'text': 'fox', 'text_offset': 217, 'audio_offset': 0.0071112, 'boundary_type': 'word'}
{'text': 'jumped', 'text_offset': 221, 'audio_offset': 0.0090484, 'boundary_type': 'word'}
{'text': 'over', 'text_offset': 228, 'audio_offset': 0.0115853, 'boundary_type': 'word'}
Currently: {'text': 'over', 'text_offset': 228, 'audio_offset': 0.0115853, 'boundary_type': 'word'}
text_offset: 221.0: The quick brown fox jumped 
{'text': 'The', 'text_offset': 201, 'audio_offset': 0.0005, 'boundary_type': 'word'}
{'text': 'quick', 'text_offset': 205, 'audio_offset': 0.0024372, 'boundary_type': 'word'}
{'text': 'brown', 'text_offset': 211, 'audio_offset': 0.0047742, 'boundary_type': 'word'}
{'text': 'fox', 'text_offset': 217, 'audio_offset': 0.0071112, 'boundary_type': 'word'}
{'text': 'jumped', 'text_offset': 221, 'audio_offset': 0.0090484, 'boundary_type': 'word'}
{'text': 'over', 'text_offset': 228, 'audio_offset': 0.0115853, 'boundary_type': 'word'}
{'text': 'the', 'text_offset': 233, 'audio_offset': 0.0137224, 'boundary_type': 'word'}
Currently: {'text': 'the', 'text_offset': 233, 'audio_offset': 0.0137224, 'boundary_type': 'word'}
text_offset: 228.0: The quick brown fox jumped over 
{'text': 'The', 'text_offset': 201, 'audio_offset': 0.0005, 'boundary_type': 'word'}
{'text': 'quick', 'text_offset': 205, 'audio_offset': 0.0024372, 'boundary_type': 'word'}
{'text': 'brown', 'text_offset': 211, 'audio_offset': 0.0047742, 'boundary_type': 'word'}
{'text': 'fox', 'text_offset': 217, 'audio_offset': 0.0071112, 'boundary_type': 'word'}
{'text': 'jumped', 'text_offset': 221, 'audio_offset': 0.0090484, 'boundary_type': 'word'}
{'text': 'over', 'text_offset': 228, 'audio_offset': 0.0115853, 'boundary_type': 'word'}
{'text': 'the', 'text_offset': 233, 'audio_offset': 0.0137224, 'boundary_type': 'word'}
{'text': 'lay', 'text_offset': 237, 'audio_offset': 0.0156596, 'boundary_type': 'word'}
Currently: {'text': 'lay', 'text_offset': 237, 'audio_offset': 0.0156596, 'boundary_type': 'word'}
text_offset: 233.0: The quick brown fox jumped over the 
{'text': 'The', 'text_offset': 201, 'audio_offset': 0.0005, 'boundary_type': 'word'}
{'text':  [...]

2023-09-21 06:13 UTC, ripperdoc commented
Thanks for your proposed MRE. I start by comparing the code you are running in your example with what's actually running in azure_synthesizer and to me it looks like your code it not just an excerpt, but it changes the behaviour from the original code.

Your code defines a global pool which is explicitly reused for two messages - I can see how that creates problems. But the orginal code creates a new pool for every message it receives, as you see in:

2023-10-04 07:27 UTC, closed without merging