change logger level from warning to info for save_as_wav
fictive-reality/vocode-python pull request #11
Opened 2023-09-13 05:17 UTC by julifr

Previously, logging will raise Error when attempting to save empty `.wav` file containing 0 bytes.

This commit proposes to lower this to `info`, and returns `None` when `audio_date == 0`.

Currently, we have that `azure_synthesizer.py` returns `SynthesisResult` containing                 `self.empty_generator()`, where the size of the `ChunkResult` is `0` which is not `None`.

This condition is triggered by `if not re.search(r"\w", message.text)`:
Which includes non-alphanumeric characters such as `.`, `-` or ` `. 
So, characters that cannot be pronounced by the synthesizer are omitted.

2023-09-13 06:36 UTC, ripperdoc requested changes
Change: Hiding the error is not the solution here. The code that calls `save_as_wav`, in `streaming_conversation.py:L153`, will not know that it failed, and will still save a path for this nonexistent file to the database. This will cause an upload failure later. Instead, you need to detect handle this as early as possible. Our current assumption is that a transcription with duration must have `audio_data`, and appears to be wrong in this case. Either we should ensure duration is set to 0 by azure_synthesizer (if we can detect there that it is empty), or we need to change the code in `streaming_conversation.py` to check what it gets from `trim_audio` before it decides to save the file path.

2023-09-13 07:46 UTC, ripperdoc commented
> Change: Hiding the error is not the solution here. The code that calls `save_as_wav`, in `streaming_conversation.py:L153`, will not know that it failed, and will still save a path for this nonexistent file to the database. This will cause an upload failure later. Instead, you need to handle this as early as possible. Our current assumption is that a transcription with duration must have `audio_data`, and that appears to be wrong in this case. Either we should ensure duration is set to 0 by azure_synthesizer (if we can detect there that it is empty), or we need to change the code in `streaming_conversation.py` to check what it gets from `trim_audio` before it decides to save the file path. Or both, for maximum safety.

Sorry, I was confused here, I'm referring to lines that deal with user transcript, not the synthesized audio, sorry for that! The principle should be the same though - we need to ensure we don't save a path into the metadata that doesn't exist, then we should not save a path at all. @julifr

2023-09-14 01:59 UTC, julifr commented
> > Change: Hiding the error is not the solution here. The code that calls `save_as_wav`, in `streaming_conversation.py:L153`, will not know that it failed, and will still save a path for this nonexistent file to the database. This will cause an upload failure later. Instead, you need to handle this as early as possible. Our current assumption is that a transcription with duration must have `audio_data`, and that appears to be wrong in this case. Either we should ensure duration is set to 0 by azure_synthesizer (if we can detect there that it is empty), or we need to change the code in `streaming_conversation.py` to check what it gets from `trim_audio` before it decides to save the file path. Or both, for maximum safety.
> 
> Sorry, I was confused here, I'm referring to lines that deal with user transcript, not the synthesized audio, sorry for that! The principle should be the same though - we need to ensure we don't save a path into the metadata that doesn't exist, then we should not save a path at all. @julifr

Just to reiterate your point:
* This only affects synthesizer.
* Not human transcript.

It makes more sense to bypass the entire audio chain if there's no alphanumeric characters that can be pronounced by the synthesizer.

Changes to `streaming_conversation.py` illustrate how we would align this with output into `azure_synthesizer.py`.

Consider the following cases:
1. Valid input -> Valid chunk -> Valid synthesis -> Valid path + wav
2. Valid input -> Valid chunk + Empty Chunk -> Valid synthesis -> Valid path + wav
3. Invalid input -> Empty Chunk -> Invalid synthesis -> Invalid path + wav

Valid input may still generate empty chunks due to sentence/word boundary events.
Previously, `caching_synthesizer.py` rendered each individual `.wav` files for each `ChunkResult`.
If any chunk returns 0, this raises the Exception for rendering an empty `.wav`

Revisions:
- Lambda function changes from `all_bytes` to `when_finished`
- `save_as_wav` runs on condition `when_finished > 0`.

Otherwise, raising the exception at the `path` stage or during a `SynthesisResult` event causes numerous side-effects.

This proposal resolves:
* Intentional side-effects from invalid input via `empty_generator()` within `azure_synthesizer.py`, that may occur during `create_speech`
* Bypasses audio chain if there's only invalid input.

2023-09-14 02:26 UTC, julifr commented
Here is a rendering of a flowchart that describes the proposal:
<img width="217" alt="Screenshot 2023-09-13 at 7 25 55 PM" src="https://github.com/fictive-reality/vocode-python/assets/141594308/3ac68f56-455c-49e5-b195-8a08ca55fd0b">

2023-09-14 18:24 UTC, ripperdoc reviewed
I haven't been able to test this one yet, just looked at the code. I'm feeling a bit of disconnect between the long winded explanation on the PR and what changes are actually in the code. I would still look for a more concise explanation to match a concise solution.

2023-09-14 18:24 UTC, ripperdoc commented on vocode/streaming/streaming_conversation.py
> +                self.conversation.logger.debug(f"total_audio_bytes: {self.conversation.total_audio_bytes}")
Do we need these debug logging? We should only keep what's necessary to not spam the log files for later.

2023-09-14 18:24 UTC, ripperdoc commented on vocode/streaming/streaming_conversation.py
> +                    self.conversation.synthesis_enabled == False
Changing in conversation changes the whole conversation state, so where is this synthesis enabled again?

2023-09-14 18:24 UTC, ripperdoc commented on vocode/streaming/utils/__init__.py
> +        return None
Returning None is not generally needed, unless we specifically need to check for None values on the calling side.

2023-09-14 18:24 UTC, ripperdoc commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +                 ):
These changes doesn't seem to have a purpose re: the solution?

2023-09-14 18:36 UTC, julifr commented on vocode/streaming/streaming_conversation.py
> +                self.conversation.logger.debug(f"total_audio_bytes: {self.conversation.total_audio_bytes}")
Removed.

2023-09-14 18:36 UTC, julifr commented on vocode/streaming/utils/__init__.py
> +        return None
Removed.

2023-09-14 18:36 UTC, julifr commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +                 ):
Removed.

2023-09-15 00:32 UTC, julifr reviewed
Moved alphanumeric flag so that audio is only sent to output on valid input.

Otherwise, message is passed through as-is a though it were a chat message with no audio.

2023-09-15 00:32 UTC, julifr commented on vocode/streaming/streaming_conversation.py
> +                    self.conversation.synthesis_enabled == False
Synthesis will re-engage on additional input, but you are correct, this would only block the audio chain without appending the message.

Removed.

2023-09-15 00:34 UTC, julifr reviewed
Reviewed accepted, change submitted.

2023-09-18 09:39 UTC, ripperdoc requested changes
Made a code comment that, in short, asks whether we should detect this error earlier instead. But let me describe more what I'm looking for - it again comes back to Minimal Reproducible Error and the chain of events that causes an error (especially important for Vocode, because a) it's written with concurrency which means it's hard to track what happens in which order and b) it's upstream code so we need to be super clear when and why we change it).

First, the error (symptom) we're seeing is that we save empty WAV files because of empty texts (also ending up naming files `synth__<hash>.wav` because the text is empty).

So as I read the code, the chain of events are something like this:
1. A player transcript is sent to the agent
2. Agent responds, and as we use `generate_responses` it will stream/split it's responses into multiple messages. In OpenAI this uses sentence splitting logic.
3. Each message is sent to `AgentResponseWorker.process`.
4. The message is used to create a `synthesis_result` which includes a generator, now starting to generate multiple audio chunks.
5. The `synthesis_result` is sent on to `SynthesisResultsWorker.process`. Here the `synthesis_result` is further passed on to actuallt transmit the audio as it's generated to the output (`send_speech_to_output`), and we also log the message to the transcript based of the result of the `send_speech_to_output`.
6. Within `send_speech_to_output` we end finalizing the generator in `synthesis_result`, which in turn calls `save_as_wav` to save the audio. The audio is named after the text content (via the `cache_key` method) and then saved to disk.
7. Via the events sent to transcript, in `convai-vocode` we pickup the message including the path to the saved file, and upload it to Google storage.

The symptom we see happens in step 6 and 7, but the source of error is more likely in step 2 or 3. There seems to be no valid case were the agent should produce an empty message, or if it should, maybe we should handle it better there. If we did, there would be no empty messages breaking logic in later steps.

The error log in `save_as_wav` should be there, because there is no valid case where we should have come this far and still try to save the audio, so we want to report it as an anomaly.

So is it feasible to catch this error in step 2/3? If we do, should we or should we not send an empty message to transcript? My gut says we should NOT because it just confuses users or other systems, but it depends slightly on the reasons why we get an empty message in the first place, which is why I need some analysis on why this happens.

2023-09-18 09:39 UTC, ripperdoc commented on vocode/streaming/streaming_conversation.py
> +                if re.search(r"\w", message.text):
This solution looks workable, but is this the right place to skip? It seems we already have synthesized the audio at this stage. Spontaneously, it sounds better to never synthesize at all if we have an empty message, e.g. in `AgentResponsesWorker.process`. But maybe something else is making it difficult to do there? Also, why do we get an empty message in the first place? Is it because agent responded with empty string or is it because of the way agent is set up to split sentences into messages (this sounds more likely, because it can break in many ways).

2023-10-16 12:42 UTC, closed without merging