Bugfix/unclosed connection
fictive-reality/vocode-python pull request #17
Opened 2024-03-20 12:58 UTC by manuel-fictive

2024-03-21 08:43 UTC, ripperdoc requested changes
This is not a working upgrade of OpenAI to me. Apart from the individual comments and errors mentioned below, I have two additional concerns:
1. There still seem to be references to the old openai SDK in the project. As far as I understand, `ChatCompletion.acreate` method is gone and replaced with `completions.create`, but there are several places left in the code where `acreate` is called. You need to go through every file that references openai and update all references - unless I'm mistaken?
2. While not in this repo - `convai-vocode` also has references to old openai SDK, including inside `eval` folder. These also need to be updated.

2024-03-21 08:43 UTC, ripperdoc commented on vocode/streaming/agent/chat_gpt_agent.py
> +        client = openai.AsyncAzureOpenAI(
I switched vocode-python to this branch, ran poetry install again, and then started the server but got:
```
  File "/Users/martin/dev/fictive/vocode-python/vocode/streaming/agent/chat_gpt_agent.py", line 167, in generate_response
    client = openai.AsyncAzureOpenAI(
             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'AsyncAzureOpenAI'
```

Additionally, it looks like this code only does Azure OpenAI and that is not the behaviour we want - we want to be able to switch between OpenAI and Azure OpenAI based on the config parameter.

2024-03-21 08:43 UTC, ripperdoc commented on vocode/streaming/agent/chat_gpt_agent.py
> +        for sentence in response_text_by_sentence:
This looks like it's NOT a streaming response, but that you switched back to a synchronized response. That is not a change we want (including changes to the response chunker). Besides - for non-streaming responses we have the other method called just `def respond` and I don't see that you changed any code there, wouldn't that be necessary?

2024-03-21 08:50 UTC, manuel-fictive commented on vocode/streaming/agent/chat_gpt_agent.py
> +        client = openai.AsyncAzureOpenAI(
Did you run in convai:
`pip install -e ../vocode-python`
?

2024-03-21 08:54 UTC, ripperdoc commented on vocode/streaming/agent/chat_gpt_agent.py
> +        client = openai.AsyncAzureOpenAI(
I missed that, so that solves the particular error (but instead, I get errors about embeddings API being changed, which is related to the other occurrences of openai SDK that wasn't changed, I suspect)

2024-03-21 09:00 UTC, ripperdoc commented
Regarding the commented out test code: this would be run when developing vocode-python to ensure it works. I haven't done that so far so AFAIK so in that sense we could remove it. But the more robust approach would be to update the tests to work with new OpenAI SDK, e.g. that would be required if we wanted to upstream this change.

2024-03-21 13:50 UTC, manuel-fictive commented on vocode/streaming/agent/chat_gpt_agent.py
> +        for sentence in response_text_by_sentence:
Here I would like to understand better what is exactly the difference between a response and a stream.

The way I understand it so far is that a response gets a paragraph and then we make sentences from it while a stream gets a stream of tokens that are then put together to build sentences.

2024-03-22 10:37 UTC, manuel-fictive commented
In addition to possible changes that may be needed. I have one question regarding the test that is commented out. Should I rewrite all possible tests in accordance to the new openai version? Should I test any other further parts of the code there?

2024-03-22 17:06 UTC, ripperdoc approved these changes
In general I approve the code (but haven't tested it more). But there are two comments that I think would be good to resolve first.

2024-03-22 17:06 UTC, ripperdoc commented on tests/streaming/agent/test_utils.py
> +# def create_chatgpt_openai_object(
Somehow I feel it would be good to translate this to the new API. It should be quite feasible - all the OPENAI_OBJECTS are dicts in this file but should be turned into classes from OpenAI as found here venv/lib/python3.11/site-packages/openai/types/chat/chat_completion.py , but everything else should be the same?

IF we do this we have some added security that we havenät changed behaviour with the SDK upgrade.

2024-03-27 11:50 UTC, manuel-fictive commented
This should be a complete version of the OpenAI upgrade plus all needed changes

2024-03-27 20:01 UTC, ripperdoc approved these changes
Approved again!

2024-03-28 09:46 UTC, merged