Update caching_synthesizer.py, AsyncGeneratorWrapper
fictive-reality/vocode-python pull request #6
Opened 2023-08-22 05:28 UTC by julifr

Overview:

AsyncGeneratorWrapper is a wrapper for `AsyncGenerator[ChunkResult, None])`
This is a wrapper for using AsyncGenerator, for use as an AsyncIterator.

`__anext__()` will raise `StopAsyncIteration` when the generator is empty.

Please refer to [PEP-0492](https://peps.python.org/pep-0492/)
```
Coroutines are still based on generators internally. So, before PEP 479, there was no fundamental difference between

def g1():
    yield from fut
    return 'spam'

and

def g2():
    yield from fut
    raise StopIteration('spam')

And since [PEP 479](https://peps.python.org/pep-0479) is accepted and enabled by default for coroutines, the following example will have its StopIteration wrapped into a RuntimeError

async def a1():
    await fut
    raise StopIteration('spam')

The only way to tell the outside code that the iteration has ended is to raise something other than StopIteration. Therefore, a new built-in exception class StopAsyncIteration was added.

Moreover, with semantics from [PEP 479](https://peps.python.org/pep-0479), all StopIteration exceptions raised in coroutines are wrapped in RuntimeError.
```
---

This commit attempts to resolve behavior when returning AsyncGenerator as an AsyncIterator.

2023-08-23 03:18 UTC, julifr commented
Previously, if `AsyncGeneratorWrapper` raised an `Exception`:
`self.when_finished(self.all_bytes)` would return `None`.

Placing this value outside of the Exception block allows us to retrieve the bytestring when the generator is stopped.

Replication: `send_speech_to_output` defines the following event:
```
# stop_event.is_set() == True/False
if stop_event.is_set():
               print("Interrupted, stopping text to speech after {} chunks".format(chunk_idx))
               message_sent = f"{synthesis_result.get_message_up_to(chunk_idx * seconds_per_chunk)}-"
               cut_off = True
               break
``` 
When this condition is True, `AsyncGeneratorWrapper` raises StopAsyncIteration.

We want `AsyncGeneratorWrapper` to return each chunk generated, until told to stop.
Placing this outside of the exception allows us to store them as we proceed.

Previously `save_as_wav()` would fail for uploading transcript audio during an `Exception`.
The anonymous function for `all_bytes` rejects `None`.

Passes initial tests for handling interruptions.
Expected behavior would be `.wav` files growing in duration per "chunk".
A successful pass without interruptions would yield the same number of bytes.

2023-08-24 07:09 UTC, julifr commented
@ripperdoc and I discussed whether or not overriding `__aclose__` here is the appropriate method.

[PEP-525](https://peps.python.org/pep-0525/) outlines the behavior of `aclose`.

By itself, `aclose` will not yield any values and is typically reserved for garbage collection.
Overriding this allows us to return attribute we need from the wrapper class used here.

Our concern may be that this method does not generalize to other generators.

This is initially passing tests and resolves the behavior for the transcript failing to save during interruption.

Special thank you to @ripperdoc for his insight.

2023-08-24 07:15 UTC, ripperdoc requested changes
There are a number of changes that doesn't make sense to me here, see the individual comments. I would recommend that your restore __anext__ to it's original implementation and just keep the aclose method.

2023-08-24 07:15 UTC, ripperdoc commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +                    print("self.all_bytes: "+str(len(self.all_bytes)))
PRs intended for merging to production should not have print statements, this is for local debugging only. Call the Python logger if this is something you feel we need to log every time (but I don't think so)

2023-08-24 07:15 UTC, ripperdoc commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +                    chunk_result.chunk
This statement does nothing. I think you've misunderstood the previous code. The line `self.all_bytes += chunk_result.chunk[44:] if self.remove_wav_header else chunk_result.chunk` means we assign either `chunk_result.chunk[44:]` or `chunk_result.chunk` to `self.all_bytes`. But when you change it to a normal if, nothing is assigned to all_bytes in the else case. Revert back to the original code.

2023-08-24 07:15 UTC, ripperdoc commented on vocode/streaming/synthesizer/caching_synthesizer.py
>              # if not cut_off:
I think this was left as a comment before to mark that cut_off will not be handled here. We can delete this comment or change it to explain this case.

2023-08-24 07:15 UTC, ripperdoc commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +        return chunk_result
This changes behaviour of the code vs before. It means that we return `chunk_result` even if we get an exception. My assumption is that StopAsyncIteration is raised _after_ the last chunk has returned already, which means there is no need to return the chunk here. In fact, chunk_result would be None or unassigned in this case. (this comment assumes you move __anext__ back into the try clause)

2023-08-24 07:15 UTC, ripperdoc commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +            self.when_finished(self.all_bytes)
This code says that we check if the inner generator has an aclose method, and only if, we run when_finished. But we should run when_finished regardless of the state of the inner generator - I don't see the logic why this is inside the if.

2023-08-24 07:15 UTC, ripperdoc commented on vocode/streaming/streaming_conversation.py
> +                value = synthesis_result.chunk_generator.when_finished
This assignment doesn't seem to serve any purpose. Besides, the way you assign here saves the Callable when_finished, not the returned value of the Callable, why would that be useful here?

2023-08-24 07:21 UTC, ripperdoc commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +        return chunk_result
Sorry, my bad here. Because we reraise on line 70, this line is never reached in the case of an exception. But moving it down here also serves no purpose, it would work the same if you left it were it was.

2023-08-24 07:26 UTC, julifr commented on vocode/streaming/streaming_conversation.py
> +                value = synthesis_result.chunk_generator.when_finished
Correct this can be removed.

2023-08-24 07:34 UTC, julifr commented on vocode/streaming/synthesizer/caching_synthesizer.py
>              # if not cut_off:
Yes, I believe this was an original comment. It is worth removing.

2023-08-24 07:43 UTC, julifr commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +                    print("self.all_bytes: "+str(len(self.all_bytes)))
I will remove this as well

2023-08-24 07:47 UTC, julifr commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +                    chunk_result.chunk
I'll revert this back to the original for clarity:
```
if chunk_result and chunk_result.chunk:
self.all_bytes += chunk_result.chunk[44:] if self.remove_wav_header else chunk_result.chunk
return chunk_result
```

2023-08-24 07:50 UTC, julifr commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +            self.when_finished(self.all_bytes)
I believe you are correct, this would be presuming itself. The function exists, we ask if it exists.

2023-08-24 07:50 UTC, julifr commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +            self.when_finished(self.all_bytes)
I'm going to remove this logic, we only need when_finished and garbage collection.

2023-08-24 07:58 UTC, julifr commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +        return chunk_result
Not reachable, removed.

2023-08-24 08:00 UTC, julifr commented on vocode/streaming/synthesizer/caching_synthesizer.py
> +        chunk_result = await self.generator.__anext__()
Right, otherwise this would have overlap. Reverted.

2023-08-24 17:23 UTC, merged